// File generated from our OpenAPI spec by Stainless.

package com.ours_privacy.api.services.blocking

import com.ours_privacy.api.TestServerExtension
import com.ours_privacy.api.client.okhttp.OursPrivacyOkHttpClient
import com.ours_privacy.api.core.JsonValue
import com.ours_privacy.api.models.visitor.VisitorUpsertParams
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class VisitorServiceTest {

    @Disabled("Prism tests are disabled")
    @Test
    fun upsert() {
        val client = OursPrivacyOkHttpClient.builder().baseUrl(TestServerExtension.BASE_URL).build()
        val visitorService = client.visitor()

        val response =
            visitorService.upsert(
                VisitorUpsertParams.builder()
                    .token("x")
                    .userProperties(
                        VisitorUpsertParams.UserProperties.builder()
                            .adId("ad_id")
                            .adsetId("adset_id")
                            .campaignId("campaign_id")
                            .city("city")
                            .clickid("clickid")
                            .clid("clid")
                            .companyName("company_name")
                            .consent(
                                VisitorUpsertParams.UserProperties.Consent.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .country("country")
                            .customProperties(
                                VisitorUpsertParams.UserProperties.CustomProperties.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .dateOfBirth("date_of_birth")
                            .dclid("dclid")
                            .email("email")
                            .epik("epik")
                            .externalId("external_id")
                            .fbc("fbc")
                            .fbclid("fbclid")
                            .fbp("fbp")
                            .firstName("first_name")
                            .gadSource("gad_source")
                            .gbraid("gbraid")
                            .gclid("gclid")
                            .gender("gender")
                            .ip("ip")
                            .isBot(JsonValue.from(mapOf<String, Any>()))
                            .jobTitle("job_title")
                            .lastName("last_name")
                            .liFatId("li_fat_id")
                            .msclkid("msclkid")
                            .ndclid("ndclid")
                            .phoneNumber(JsonValue.from(mapOf<String, Any>()))
                            .qclid("qclid")
                            .rdtCid("rdt_cid")
                            .referrer("referrer")
                            .sacid("sacid")
                            .sccid("sccid")
                            .sid("sid")
                            .state("state")
                            .ttclid("ttclid")
                            .twclid("twclid")
                            .userAgent("user_agent")
                            .userAgentFullList("user_agent_full_list")
                            .utmCampaign("utm_campaign")
                            .utmContent("utm_content")
                            .utmMedium("utm_medium")
                            .utmName("utm_name")
                            .utmSource("utm_source")
                            .utmTerm("utm_term")
                            .wbraid("wbraid")
                            .zip(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .defaultProperties(
                        VisitorUpsertParams.DefaultProperties.builder()
                            .activeDuration(0.0)
                            .adId("ad_id")
                            .adsetId("adset_id")
                            .browserLanguage("browser_language")
                            .browserName("browser_name")
                            .browserVersion("browser_version")
                            .campaignId("campaign_id")
                            .clickid("clickid")
                            .clid("clid")
                            .cpuArchitecture("cpu_architecture")
                            .currentUrl("current_url")
                            .dclid("dclid")
                            .deviceModel("device_model")
                            .deviceType("device_type")
                            .deviceVendor("device_vendor")
                            .duration(0.0)
                            .encoding("encoding")
                            .engineName("engine_name")
                            .engineVersion("engine_version")
                            .epik("epik")
                            .fbc("fbc")
                            .fbclid("fbclid")
                            .fbp("fbp")
                            .fv(true)
                            .gadSource("gad_source")
                            .gbraid("gbraid")
                            .gclid("gclid")
                            .host("host")
                            .iframe(true)
                            .ip("ip")
                            .isBot(JsonValue.from(mapOf<String, Any>()))
                            .liFatId("li_fat_id")
                            .msclkid("msclkid")
                            .ndclid("ndclid")
                            .newS(true)
                            .osName("os_name")
                            .osVersion("os_version")
                            .pageHash(0.0)
                            .pathname("pathname")
                            .qclid("qclid")
                            .rdtCid("rdt_cid")
                            .receivedAt("received_at")
                            .referrer("referrer")
                            .sacid("sacid")
                            .sccid("sccid")
                            .screenHeight(0.0)
                            .screenWidth(0.0)
                            .sessionCount(0.0)
                            .sid("sid")
                            .sr("sr")
                            .title("title")
                            .ttclid("ttclid")
                            .twclid("twclid")
                            .uafvl("uafvl")
                            .userAgent("user_agent")
                            .utmCampaign("utm_campaign")
                            .utmContent("utm_content")
                            .utmMedium("utm_medium")
                            .utmName("utm_name")
                            .utmSource("utm_source")
                            .utmTerm("utm_term")
                            .version("version")
                            .wbraid("wbraid")
                            .webview(true)
                            .build()
                    )
                    .email("x")
                    .externalId("x")
                    .userId("x")
                    .build()
            )

        response.validate()
    }
}
