// File generated from our OpenAPI spec by Stainless.

package com.oursprivacy.services.blocking

import com.oursprivacy.client.okhttp.OursPrivacyOkHttpClient
import com.oursprivacy.core.JsonValue
import com.oursprivacy.models.batch.BatchCreateParams
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class BatchServiceTest {

    @Disabled("Mock server tests are disabled")
    @Test
    fun create() {
        val client = OursPrivacyOkHttpClient.fromEnv()
        val batchService = client.batch()

        val batch =
            batchService.create(
                BatchCreateParams.builder()
                    .token("x")
                    .addEvent(
                        BatchCreateParams.Event.builder()
                            .event("x")
                            .token("x")
                            .defaultProperties(
                                BatchCreateParams.Event.DefaultProperties.builder()
                                    .activeDuration(0.0)
                                    .adId("ad_id")
                                    .admitadUid("admitad_uid")
                                    .adsetId("adset_id")
                                    .alart("alart")
                                    .aleid("aleid")
                                    .axwrt("axwrt")
                                    .basisCid("basis_cid")
                                    .browserLanguage("browser_language")
                                    .browserName("browser_name")
                                    .browserVersion("browser_version")
                                    .campaignId("campaign_id")
                                    .clickid("clickid")
                                    .clid("clid")
                                    .cpuArchitecture("cpu_architecture")
                                    .currentUrl("current_url")
                                    .dclid("dclid")
                                    .deviceModel("device_model")
                                    .deviceType("device_type")
                                    .deviceVendor("device_vendor")
                                    .duration(0.0)
                                    .encoding("encoding")
                                    .engineName("engine_name")
                                    .engineVersion("engine_version")
                                    .epik("epik")
                                    .fbc("fbc")
                                    .fbclid("fbclid")
                                    .fbp("fbp")
                                    .fv(true)
                                    .gadSource("gad_source")
                                    .gbraid("gbraid")
                                    .gclid("gclid")
                                    .host("host")
                                    .iframe(true)
                                    .imRef("im_ref")
                                    .ip("ip")
                                    .irclickid("irclickid")
                                    .isBot("is_bot")
                                    .liFatId("li_fat_id")
                                    .msclkid("msclkid")
                                    .ndclid("ndclid")
                                    .newS(true)
                                    .osName("os_name")
                                    .osVersion("os_version")
                                    .pageHash(0.0)
                                    .pathname("pathname")
                                    .qclid("qclid")
                                    .rdtCid("rdt_cid")
                                    .receivedAt("received_at")
                                    .referrer("referrer")
                                    .referringDomain("referring_domain")
                                    .sacid("sacid")
                                    .sccid("sccid")
                                    .screenHeight(0.0)
                                    .screenWidth(0.0)
                                    .sessionCount(0.0)
                                    .sid("sid")
                                    .sr("sr")
                                    .title("title")
                                    .ttclid("ttclid")
                                    .twclid("twclid")
                                    .uafvl("uafvl")
                                    .userAgent("user_agent")
                                    .utmCampaign("utm_campaign")
                                    .utmContent("utm_content")
                                    .utmMedium("utm_medium")
                                    .utmName("utm_name")
                                    .utmSource("utm_source")
                                    .utmTerm("utm_term")
                                    .version("version")
                                    .wbraid("wbraid")
                                    .webview(true)
                                    .build()
                            )
                            .distinctId("x")
                            .email("x")
                            .eventProperties(
                                BatchCreateParams.Event.EventProperties.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .externalId("x")
                            .identityContext(
                                BatchCreateParams.Event.IdentityContext.builder()
                                    .ip("ip")
                                    .userAgent("userAgent")
                                    .build()
                            )
                            .time(0.0)
                            .userId("x")
                            .userProperties(
                                BatchCreateParams.Event.UserProperties.builder()
                                    .adId("ad_id")
                                    .admitadUid("admitad_uid")
                                    .adsetId("adset_id")
                                    .alart("alart")
                                    .aleid("aleid")
                                    .axwrt("axwrt")
                                    .basisCid("basis_cid")
                                    .campaignId("campaign_id")
                                    .city("city")
                                    .clickid("clickid")
                                    .clid("clid")
                                    .companyName("company_name")
                                    .consent(
                                        BatchCreateParams.Event.UserProperties.Consent.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .country("country")
                                    .customProperties(
                                        BatchCreateParams.Event.UserProperties.CustomProperties
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .dateOfBirth("date_of_birth")
                                    .dclid("dclid")
                                    .email("email")
                                    .epik("epik")
                                    .externalId("external_id")
                                    .fbc("fbc")
                                    .fbclid("fbclid")
                                    .fbp("fbp")
                                    .firstName("first_name")
                                    .gadSource("gad_source")
                                    .gbraid("gbraid")
                                    .gclid("gclid")
                                    .gender("gender")
                                    .imRef("im_ref")
                                    .ip("ip")
                                    .irclickid("irclickid")
                                    .isBot("is_bot")
                                    .jobTitle("job_title")
                                    .lastName("last_name")
                                    .liFatId("li_fat_id")
                                    .msclkid("msclkid")
                                    .ndclid("ndclid")
                                    .phoneNumber("phone_number")
                                    .qclid("qclid")
                                    .rdtCid("rdt_cid")
                                    .referrer("referrer")
                                    .referringDomain("referring_domain")
                                    .sacid("sacid")
                                    .sccid("sccid")
                                    .sid("sid")
                                    .state("state")
                                    .ttclid("ttclid")
                                    .twclid("twclid")
                                    .userAgent("user_agent")
                                    .userAgentFullList("user_agent_full_list")
                                    .utmCampaign("utm_campaign")
                                    .utmContent("utm_content")
                                    .utmMedium("utm_medium")
                                    .utmName("utm_name")
                                    .utmSource("utm_source")
                                    .utmTerm("utm_term")
                                    .wbraid("wbraid")
                                    .zip("zip")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )

        batch.validate()
    }
}
